import { Inter } from "next/font/google"
import "./globals.css"
import { SessionProvider } from 'next-auth/react'
import { auth } from '../lib/auth'
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout ({ children }) {
  const session = await auth()
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={inter.className}>{children}</body>
      </SessionProvider>
    </html>
  )
}
